# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

weird1compute <- function(m, v, h) {
    .Call(`_ngvb_weird1compute`, m, v, h)
}

weird2compute <- function(m, v, h) {
    .Call(`_ngvb_weird2compute`, m, v, h)
}

